/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pFinal.paint_basico_2d;

import java.awt.AWTException;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Robot;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import sm.ffm.graficos.MyShape;
import sm.ffm.iu.LienzoImagen2D;

/**
 *
 * @author francisco
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    VentanaPrincipal vPrincipal = null;
    private BasicStroke strokeVPrincipal;
    private List<MyShape> listaShapes = new ArrayList();
    
    public VentanaInterna(VentanaPrincipal vp) {
        initComponents();
        this.vPrincipal = vp;
        vp.btnElipse.isSelected();
        vp.listaFiguras.removeAllItems();
        this.getLienzo2D().setHerrSelec(LienzoImagen2D.herramientasDibujo.LAPIZ);
    }
    
    public LienzoImagen2D getLienzo2D(){
        return this.lienzo2D;
    }
    
    public void actualizarListaFormas(){
        if(this.getLienzo2D().getvShape() != null){
            this.listaShapes = this.getLienzo2D().getvShape();
            System.out.println(this.listaShapes.size());
            if(vPrincipal != null){
                vPrincipal.listaFiguras.removeAllItems();
                if(this.listaShapes != null){
                    for(MyShape s:listaShapes){
                        vPrincipal.listaFiguras.addItem(s);
                    }
                }
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollVentInterna = new javax.swing.JScrollPane();
        lienzo2D = new sm.ffm.iu.LienzoImagen2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lienzo2D.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2DMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        scrollVentInterna.setViewportView(lienzo2D);

        getContentPane().add(scrollVentInterna, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        if(this.vPrincipal != null){
            this.getLienzo2D().addLienzoListener(vPrincipal.manejador);
            if(this.getLienzo2D().getHerrSelec() != null){
                switch (this.getLienzo2D().getHerrSelec()){
                    case LAPIZ:
                        this.vPrincipal.btnLapiz.setSelected(true); 
                        this.vPrincipal.txtBarraEstado.setText("Lápiz");
                        break;
                    case LINEA:
                        this.vPrincipal.btnLinea.setSelected(true); 
                        this.vPrincipal.txtBarraEstado.setText("Línea");
                        break;
                    case RECTANGULO:
                        this.vPrincipal.btnRectangulo.setSelected(true);
                        this.vPrincipal.txtBarraEstado.setText("Rectángulo");
                        break;
                    case ELIPSE:
                        this.vPrincipal.btnElipse.setSelected(true); 
                        this.vPrincipal.txtBarraEstado.setText("Elipse");
                        break;
                }
            }
            
            this.vPrincipal.listaColores.setSelectedItem(this.getLienzo2D().getColorTrazo());
            this.actualizarListaFormas();
            
            this.strokeVPrincipal = (BasicStroke)this.getLienzo2D().getGrosor();
            this.vPrincipal.spinnerGrosor.setValue((int) strokeVPrincipal.getLineWidth());
            
            this.vPrincipal.btnEditar.setSelected(this.getLienzo2D().getEditar());
            this.vPrincipal.btnTransparencia.setSelected(this.getLienzo2D().getTransparencia());
            this.vPrincipal.btnAlisado.setSelected(this.getLienzo2D().getAlisar());
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzo2DMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseMoved
        try {
            Color c;
            Robot r = new Robot();
            c = r.getPixelColor(evt.getXOnScreen(), evt.getYOnScreen());
            
            this.vPrincipal.txtValorRGB.setText("R:" + c.getRed() + " G:" + c.getGreen() + " B:" + c.getBlue());
        } catch (AWTException ex) {
            Logger.getLogger(VentanaInterna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lienzo2DMouseMoved

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.vPrincipal.listaFiguras.removeAllItems();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.ffm.iu.LienzoImagen2D lienzo2D;
    private javax.swing.JScrollPane scrollVentInterna;
    // End of variables declaration//GEN-END:variables
}
